### ISSUE TITLE
Planning class 7 & 8

### ISSUE THREAD

**Issue by KevinTss** [HackYourFutureBelgium/improvements#1]
@colevandersWands Can you perhaps share the dates when the class will start to have more info about timeline that we have to respect?

**Comment by colevandersWands** [comment]
January 5th, two new classes will be starting.  class 7 & 8

their class repos: [class 7](https://github.com/hackyourfuturebelgium/class-7), [class 8](https://github.com/hackyourfuturebelgium/class-8)
